server:
  port: 7001
spring:
  application:
    name: cqrs-write
  rabbitmq:
    addresses: rabbitmq
    username: user
    password: wfrfqm6HXn
  cloud:
    stream:
      bindings:
        healthCheckMessageProducer:
          destination: spring-starter
          contentType: application/json
        healthCheckMessageConsumer:
          destination: spring-starter
          group: health-check-group
          durableSubscription: true
        cqrsWriteProducer:
          destination: cqrs.write
          contentType: application/json
      rabbit:
        bindings:
          cqrsWriteProducer:
            producer:
              exchangeAutoDelete: false
              exchangeDurable: true
              exchangeType: topic
  jackson:
    serialization.write_dates_as_timestamps: false
    deserialization.adjust_dates_to_context_time_zone: false
spring.sleuth.web.skipPattern: /ping|/favicon.ico|

starter.service.props.testValue: dev.value

logging.level.com.sprinthive: DEBUG
